[build]
  command = "npm run build"
  publish = "out"

[functions]
  directory = "netlify/functions"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://igthouwddtjftxaxuhqf.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_anon_key_here"

[[redirects]]
  from = "/api/sheets/import"
  to = "/.netlify/functions/sheets-import"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200