[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://igthouwddtjftxaxuhqf.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_anon_key_here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200