[build]
  command = "npm run build"
  publish = "out"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/sheets/import"
  to = "/.netlify/functions/sheets-import"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200